[workspace]
members = ["rust/core", "rust/headless", "rust/python"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "MIT"

[workspace.dependencies]
revm = { version = "=43.0.2", default-features = false, features = ["std"] }
sevm-revm-core = { path = "rust/core" }
sevm-revm-headless = { path = "rust/headless" }
